import {
  setPrayers,
  getAllPrayers,
  addPrayer,
  upDatePrayer,
  updatePrayersInStore,
  removePrayer,
  getPrayerById,
  setCurrentPrayer,
  addComment,
  setError,
  setLoading,
  cleareCurrentPrayer,
  updateCurrentPrayers,
  addCommentToCurrentPrayers,
} from './prayerSlice';

export {
  setPrayers,
  getAllPrayers,
  addPrayer,
  upDatePrayer,
  updatePrayersInStore,
  removePrayer,
  getPrayerById,
  setCurrentPrayer,
  addComment,
  setError,
  setLoading,
  cleareCurrentPrayer,
  updateCurrentPrayers,
  addCommentToCurrentPrayers,
};
